#! /usr/bin/python -tt

# timezones
# Displays zoneinfo time zone names

# Copyright 2009 Richard Fearn
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
import pytz

if len(sys.argv) not in (1, 2):
	print >>sys.stderr, "usage: timezones [text]"
	sys.exit(1)

if len(sys.argv) == 2:
	text = sys.argv[1]
	matches = [tz for tz in pytz.all_timezones if text.lower() in tz.lower()]
else:
	matches = pytz.all_timezones

for m in matches:
	print m
